### ISSUE TITLE
What does d.RESET() actually do?

### ISSUE THREAD

**Issue by hichiaty** [atlas0fd00m/rfcat#84] opened 2020-10-05 16:37 UTC
Hi,

I just bought a Yardstick one, it was detected fine and working but I kept recieving USB Timeout errors every other command, so I thought I'd try d.RESET(), now it's not detected at all! Have I just deleted the firmware? 

Any help is appreciated.

Thanks

**Comment by hichiaty** [comment] 2020-10-05 16:41
Ok, an unplug/replug and system reboot seems to have worked, but still wondering what it actually does?

**Comment by hichiaty** [comment] 2020-10-05 16:53
Now it broke again, I am unable to even d.ping(), `Ping Failed. Timeout waiting for USB response.`
 anyone know what is happening?

**Comment by atlas0fd00m** [comment] 2020-10-05 16:54
can you attach a screenshot?

**Comment by hichiaty** [comment] 2020-10-05 18:09
Ok, I am using a Raspberry pi zero w and ssh from my windows 10 machine.

![image](https://user-images.githubusercontent.com/21251528/95116014-490eb700-073e-11eb-8bbc-9b1ba1741953.png)

**Comment by hichiaty** [comment] 2020-10-05 18:24
This is my `lsusb` 
![image](https://user-images.githubusercontent.com/21251528/95117371-65abee80-0740-11eb-830e-53eae273f938.png)

**Comment by hichiaty** [comment] 2020-10-05 18:32
after a reboot, it worked for about 5 seconds then stopped.
![image](https://user-images.githubusercontent.com/21251528/95118016-6ee98b00-0741-11eb-9640-1ba969cd4f4a.png)

**Comment by hichiaty** [comment] 2020-10-05 18:37
and this is my radio config.... when it works:

```
In [5]: print(d.reprRadioConfig())
== Hardware ==
Dongle:              YARDSTICKONE
Firmware rev:        0348
Compiler:            Not found! Update needed!
Bootloader:          CC-Bootloader

== Software ==
rflib rev:           603

== Frequency Configuration ==
Frequency:           433924804.687500 hz (0x121488)
Channel:             0
Intermediate freq:   281250 hz
Frequency Offset:    0 +/-
Est. Freq Offset:    245

== Modem Configuration ==
Modulation:          2FSK
DRate:               499511.718750 hz
ChanBW:              93750.000000 hz
DEVIATION:           20507.812500 hz
Sync Mode:           Carrier Detect
Min TX Preamble:     4 bytes
Chan Spacing:        199951.171875 hz
BSLimit:             No data rate offset compensation performed
DC Filter:           enabled
Manchester Encoding: disabled
Fwd Err Correct:     disabled

== Packet Configuration ==
Sync Word:           0xAAAA
Packet Length:       250
Length Config:       Fixed Packet Mode
Configured Address:  0x0
Preamble Quality Threshold: 4 * 0
Append Status:       No
Rcvd Packet Check:   No address check
Data Whitening:      off
Packet Format:       Normal mode
CRC:                 disabled

== AES Crypto Configuration ==
AES Mode:            CBC - Cipher Block Chaining
Crypt RF Input:      off
Crypt RF Output:     off

== Radio Test Signal Configuration ==
TEST2:               0x88
TEST1:               0x31
TEST0:               0x9
VCO_SEL_CAL_EN:      0x0

== Radio State ==
     MARCSTATE:      MARC_STATE_RX (d)
     DONGLE RESPONDING:  mode :d, last error# 1

== Client State ==
========================================================================================================================
     client thread cycles:      326/60
     client errored cycles:     0
     recv_queue:                (0 bytes) ''
     trash:                     (3 blobs) "[128, 142, (1601922839.886627, '')]"
     recv_mbox                  (2 keys)  "['0x42', '0xff']"
       app 0x42 (1 records)
             [0x7]    (0 frames)  "[]"

       app 0xff (5 records)
             [0x88]    (0 frames)  "[]"
             [0x80]    (0 frames)  "[]"
             [0x82]    (0 frames)  "[]"
             [0x86]    (0 frames)  "[]"
             [0x81]    (0 frames)  "[]"


In [6]:```

**Comment by atlas0fd00m** [comment] 2020-10-05 22:02
can you do a dump from where it works to when it doesn't?

**Comment by hichiaty** [comment] 2020-10-08 11:35
@atlas0fd00m I have now dual booted Ubuntu with my windows machine and it seems to work fine on there, I guess the issue was with the raspberry pi, as in issue #52. it's such a shame that it does not work with raspberry pi's, do you have any idea of why that is the case?

**Comment by atlas0fd00m** [comment] 2020-10-08 20:58
no, i wish i knew.  i don't spend enough time on Pi's to meaningfully troubleshoot, but i'm happy to work with someone who can put in the time and effort to track down what's going on.

**Comment by maaxxyy** [comment] 2020-11-02 02:10
Hi atlas0fd00m, i'd be happy to help with YS1 and pi as i am having issues myself. See my other post, it used to work fine on pi 3, but since the pyside2 is unavailable, i've been having loads of issues.

**Comment by ma77carpenter** [comment] 2020-11-02 20:23
thank you, @maaxxyy , i appreciate the offer, and will take you up on it.

should we have the conversation here or on irc?  (freenode: #rfcat)

**Comment by maaxxyy** [comment] 2020-11-02 23:30
Hi, I have never used irc if I'm totally honest. I'm Paul by the way. A little insight in to what I have in relation to rf.

1. nooelec.com smart sdr
2. yard stick one
3. raspberry pi 3 b+
4. hackrf one + portapack h1 + rtlsdr blog wideband LNA
5. cc1101 dev boards
6. lots of arduino, uno, mini etc     plus 315, 433mhz tx rx boards.
7. cc debugger

Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Matthew Carpenter <notifications@github.com> Date: 02/11/2020  20:23  (GMT+00:00) To: atlas0fd00m/rfcat <rfcat@noreply.github.com> Cc: maaxxyy <phh1972@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [atlas0fd00m/rfcat] What does d.RESET() actually do? (#84) 
thank you, @maaxxyy , i appreciate the offer, and will take you up on it.
should we have the conversation here or on irc?  (freenode: #rfcat)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/atlas0fd00m/rfcat/issues/84#issuecomment-720703790",
"url": "https://github.com/atlas0fd00m/rfcat/issues/84#issuecomment-720703790",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by atlas0fd00m** [comment] 2020-11-03 13:33
thank you, @maaxxyy 
that's a great set of tools :)
are you very familiar with using the cc debugger?
how about Wireshark for tracing USB?

do you have any understanding of USB?

you should be able to understand a bit of what the code is doing using Wireshark and watching the back-and-forth communication (although it can get a little overwhelming quickly).

can you reproduce the problem behavior?

**Comment by maaxxyy** [comment] 2020-11-03 14:04
Yes I have used the cc debugger but find the smartrf studio limited, probably due to my lack of knowledge in rf.I have Kali on one sd for my pi 3 running a alfa ar9271 network adapter, I have used wireshark once for packet sniffing after setting up proxychains. But not in depth, as i a very beginner hacker.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: atlas0fd00m <notifications@github.com> Date: 03/11/2020  13:33  (GMT+00:00) To: atlas0fd00m/rfcat <rfcat@noreply.github.com> Cc: maaxxyy <phh1972@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [atlas0fd00m/rfcat] What does d.RESET() actually do? (#84) 
thank you, @maaxxyy
that's a great set of tools :)
are you very familiar with using the cc debugger?
how about Wireshark for tracing USB?
do you have any understanding of USB?
you should be able to understand a bit of what the code is doing using Wireshark and watching the back-and-forth communication (although it can get a little overwhelming quickly).
can you reproduce the problem behavior?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/atlas0fd00m/rfcat/issues/84#issuecomment-721117902",
"url": "https://github.com/atlas0fd00m/rfcat/issues/84#issuecomment-721117902",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by maaxxyy** [comment] 2020-11-05 21:39
Are you aware if a work around for PySide2 not being available for linux? As I running into issues with on my pi 3, also I want to install react on a linux laptop but I think it will fail due to PySide2 not being available. Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: atlas0fd00m <notifications@github.com> Date: 03/11/2020  13:33  (GMT+00:00) To: atlas0fd00m/rfcat <rfcat@noreply.github.com> Cc: maaxxyy <phh1972@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [atlas0fd00m/rfcat] What does d.RESET() actually do? (#84) 
thank you, @maaxxyy
that's a great set of tools :)
are you very familiar with using the cc debugger?
how about Wireshark for tracing USB?
do you have any understanding of USB?
you should be able to understand a bit of what the code is doing using Wireshark and watching the back-and-forth communication (although it can get a little overwhelming quickly).
can you reproduce the problem behavior?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/atlas0fd00m/rfcat/issues/84#issuecomment-721117902",
"url": "https://github.com/atlas0fd00m/rfcat/issues/84#issuecomment-721117902",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by atlas0fd00m** [comment] 2020-11-09 17:56
i'm not sure what the problem us.  i don't have any problems on Ubuntu 20.04.  
what does your system build  look like?

**Comment by maaxxyy** [comment] 2020-11-10 01:17
Hi my laptop build us Ubuntu peppermint 10 bubonic. I've had this problem with (pyside2) my pi 3 and this new laptop, very strange. I've posted my error script on github issue 38. Be great if you could help!Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: atlas0fd00m <notifications@github.com> Date: 09/11/2020  17:56  (GMT+00:00) To: atlas0fd00m/rfcat <rfcat@noreply.github.com> Cc: maaxxyy <phh1972@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [atlas0fd00m/rfcat] What does d.RESET() actually do? (#84) 
i'm not sure what the problem us.  i don't have any problems on Ubuntu 20.04.
what does your system build  look like?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/atlas0fd00m/rfcat/issues/84#issuecomment-724174708",
"url": "https://github.com/atlas0fd00m/rfcat/issues/84#issuecomment-724174708",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by atlas0fd00m** [comment] 2020-11-12 13:55
```
atlas@fangorn:~ $ virtualenv /tmp/foo
created virtual environment CPython3.8.5.final.0-64 in 183ms
  creator CPython3Posix(dest=/tmp/foo, clear=False, global=False)
  seeder FromAppData(download=False, pyparsing=latest, contextlib2=latest, setuptools=latest, six=latest, colorama=latest, pytoml=latest, retrying=latest, ipaddr=latest, wheel=latest, distro=latest, progress=latest, packaging=latest, html5lib=latest, urllib3=latest, appdirs=latest, pep517=latest, CacheControl=latest, lockfile=latest, requests=latest, pkg_resources=latest, msgpack=latest, webencodings=latest, chardet=latest, distlib=latest, pip=latest, certifi=latest, idna=latest, via=copy, app_data_dir=/home/atlas/.local/share/virtualenv/seed-app-data/v1.0.1.debian)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
(foo) atlas@fangorn:~ $ pip install --no-cache-dir pyside2
Collecting pyside2
  Downloading PySide2-5.15.1-5.15.1-cp35.cp36.cp37.cp38.cp39-abi3-manylinux1_x86_64.whl (165.8 MB)
     |████████████████████████████████| 165.8 MB 4.7 MB/s 
Requirement already satisfied: shiboken2==5.15.1 in /tmp/foo/lib/python3.8/site-packages (from pyside2) (5.15.1)
Installing collected packages: pyside2
Successfully installed pyside2-5.15.1
```

seems to work for me at this time.  can you send me your output?
that was for python3.  i didn't try it for python2

**Comment by maaxxyy** [comment] 2020-11-12 17:02
Thanks I'll have look later for you. Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: atlas0fd00m <notifications@github.com> Date: 12/11/2020  13:55  (GMT+00:00) To: atlas0fd00m/rfcat <rfcat@noreply.github.com> Cc: maaxxyy <phh1972@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [atlas0fd00m/rfcat] What does d.RESET() actually do? (#84) 

atlas@fangorn:~ $ virtualenv /tmp/foo

created virtual environment CPython3.8.5.final.0-64 in 183ms

  creator CPython3Posix(dest=/tmp/foo, clear=False, global=False)

  seeder FromAppData(download=False, pyparsing=latest, contextlib2=latest, setuptools=latest, six=latest, colorama=latest, pytoml=latest, retrying=latest, ipaddr=latest, wheel=latest, distro=latest, progress=latest, packaging=latest, html5lib=latest, urllib3=latest, appdirs=latest, pep517=latest, CacheControl=latest, lockfile=latest, requests=latest, pkg_resources=latest, msgpack=latest, webencodings=latest, chardet=latest, distlib=latest, pip=latest, certifi=latest, idna=latest, via=copy, app_data_dir=/home/atlas/.local/share/virtualenv/seed-app-data/v1.0.1.debian)

  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

(foo) atlas@fangorn:~ $ pip install --no-cache-dir pyside2

Collecting pyside2

  Downloading PySide2-5.15.1-5.15.1-cp35.cp36.cp37.cp38.cp39-abi3-manylinux1_x86_64.whl (165.8 MB)

     |████████████████████████████████| 165.8 MB 4.7 MB/s 

Requirement already satisfied: shiboken2==5.15.1 in /tmp/foo/lib/python3.8/site-packages (from pyside2) (5.15.1)

Installing collected packages: pyside2

Successfully installed pyside2-5.15.1



seems to work for me at this time.  can you send me your output?

that was for python3.  i didn't try it for python2



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/atlas0fd00m/rfcat/issues/84#issuecomment-726092822",

"url": "https://github.com/atlas0fd00m/rfcat/issues/84#issuecomment-726092822",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by maaxxyy** [comment] 2020-11-13 12:11
Hi atlas I managed to get the YS1 working by using the files from - code.google.com/archive/p/rfcat/downloadsand used rfcat_130515I'm using a Asus eee pc 901 with Ubuntu 14.04 on. I'm waiting for a bigger ssd so I can install Ubuntu 16 on which pyside2 built in. I'll keep you posted how i get on with the install.Cheers Paul aka maaxxyySent from my Samsung Galaxy smartphone.
-------- Original message --------From: atlas0fd00m <notifications@github.com> Date: 12/11/2020  13:55  (GMT+00:00) To: atlas0fd00m/rfcat <rfcat@noreply.github.com> Cc: maaxxyy <phh1972@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [atlas0fd00m/rfcat] What does d.RESET() actually do? (#84) 

atlas@fangorn:~ $ virtualenv /tmp/foo

created virtual environment CPython3.8.5.final.0-64 in 183ms

  creator CPython3Posix(dest=/tmp/foo, clear=False, global=False)

  seeder FromAppData(download=False, pyparsing=latest, contextlib2=latest, setuptools=latest, six=latest, colorama=latest, pytoml=latest, retrying=latest, ipaddr=latest, wheel=latest, distro=latest, progress=latest, packaging=latest, html5lib=latest, urllib3=latest, appdirs=latest, pep517=latest, CacheControl=latest, lockfile=latest, requests=latest, pkg_resources=latest, msgpack=latest, webencodings=latest, chardet=latest, distlib=latest, pip=latest, certifi=latest, idna=latest, via=copy, app_data_dir=/home/atlas/.local/share/virtualenv/seed-app-data/v1.0.1.debian)

  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

(foo) atlas@fangorn:~ $ pip install --no-cache-dir pyside2

Collecting pyside2

  Downloading PySide2-5.15.1-5.15.1-cp35.cp36.cp37.cp38.cp39-abi3-manylinux1_x86_64.whl (165.8 MB)

     |████████████████████████████████| 165.8 MB 4.7 MB/s 

Requirement already satisfied: shiboken2==5.15.1 in /tmp/foo/lib/python3.8/site-packages (from pyside2) (5.15.1)

Installing collected packages: pyside2

Successfully installed pyside2-5.15.1



seems to work for me at this time.  can you send me your output?

that was for python3.  i didn't try it for python2



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/atlas0fd00m/rfcat/issues/84#issuecomment-726092822",

"url": "https://github.com/atlas0fd00m/rfcat/issues/84#issuecomment-726092822",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by atlas0fd00m** [comment] 2020-12-29 21:50
@maaxxyy i'm closing this for now, let me know when you get to a better state to test.

**Closed as completed by atlas0fd00m** 2020-12-29 21:50 UTC
